version: '3.7'

services:
    db-points:
        image: bitnami/postgresql:latest
        ports:
            - "5431:5432"
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=points
        volumes:
            - pg_data_points:/bitnami/postgresql
    
    db-users:
        image: bitnami/postgresql:latest
        ports:
            - "5430:5432"
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=users
        volumes:
            - pg_data_users:/bitnami/postgresql

    localstack:
        image: localstack/localstack
        ports:
            - '127.0.0.1:4566:4566' # LocalStack Gateway
            - '127.0.0.1:4510-4559:4510-4559' # external services port range
        environment:
            - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
            - DEBUG=1
        volumes:
            - './.docker/localstack/seed-messaging.sh:/etc/localstack/init/ready.d/seed-messaging.sh'

volumes:
    pg_data_points:
    pg_data_users: