version: '3.7'

services:
    db-points:
        image: bitnami/postgresql:latest
        ports:
            - "5431:5432"
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=points
        volumes:
            - pg_data_points:/bitnami/postgresql
    
    db-users:
        image: bitnami/postgresql:latest
        ports:
            - "5430:5432"
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=users
        volumes:
            - pg_data_users:/bitnami/postgresql

volumes:
    pg_data_points:
    pg_data_users: